= What is the Neo4j GraphGist Project? =

:neo4j-version: 2.1.0
:author: Clifford Anderson
:twitter: @andersoncliffb
:tags: domain:example

These are a collection of GraphGists from various projects at the http://www.library.vanderbilt.edu/[Vanderbilt University Library].
http://neo4j.com[Neo4j] GraphGists are a convenient way to create and share documents containing not just prose, structure
and pictures but most importantly **example graph models and use-cases** expressed in Neo4j's query language http://docs.neo4j.org/refcard/2.1/[Cypher].

These documents are written in AsciiDoc -- the simple, textual markup language -- and rendered in your browser as rich and interactive web pages that you can quickly evolve from describing simple howtos or questions to providing an extensive use-case specification.

=== List of our Gists ===

 http://heardlibrary.github.io/graphgist/?2d0c49d816987ba58c5b [The Epistolary Correspondence of Flannery O'Connor]

=== Setup a Graph to show you and your Likes

//setup
[source,cypher]
----
CREATE (you:Person {name:"You"})-[like:LIKE]->(us:Database:NoSql:Graph {name:"Neo4j" })
RETURN you, like, us
----

And render as a graph.

//graph

=== Now query the graph to show all the things you like

[source,cypher]
----
MATCH (you:Person {name:"You"})-[like:LIKE]->(liked)
RETURN you.name AS who, type(like) AS how, liked.name AS what
----

And render as a table.

//table

NOTE: This document is a GraphGist itself, so you can use the green https://github.com/neo4j-contrib/gists/blob/master/meta/Home.adoc[Page Source] button on top of the page to see the original AsciiDoc document.
